### ISSUE TITLE
Sorry, I can't build cargo-mirror without cargo-mirror in China.

### ISSUE THREAD

**Issue by cupen** [tennix/cargo-mirror#2]
Hey, guy. 
I can't build cargo-mirror, beacuse the resources of http://creates.io was blocked by GFW in China.

**Comment by cupen** [comment]
well,  I build cargo-mirror on my linode VPS and copy the binary to my local machine. It works fine.

**Comment by protodonuts** [comment]
Wrong URL. Use https://crates.io/ instead.

**Comment by cupen** [comment]
@protodonuts sorry, my spelling error.

我几年前要用 cargo-mirror 解决 crates 被墙的问题，结果发现构建它也需要 crates(dependencies)，所以才提这么个 issue 的，如今也用不上了，抱歉忘了关 issue 。

p.s. 都是国人我就不用我蹩脚的英文跟各位老大客套了。
